---
title: "assignment_3"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
require(ggplot2)
library(rpgm)

meter_data <- read.csv2("smart_meter_data.csv")
survey_data <- read.csv2("survey_with_smart_meter_data.csv")
```

---
Exercise 1
---
```{r setup, include=FALSE}
joined_data <- inner_join(survey_data, meter_data, by = c("ID" = "V1"))

# find null values
sapply(joined_data,function(x) sum(is.na(x)))

# Lowest Consumption
joined_data <- mutate(joined_data, lowest_consumption = rowMins(meter_data[, c(2:337)]))

# Highest Consumption
joined_data <- mutate(joined_data, highest_consumption = rowMaxs(meter_data[, c(2:337)]))

# Mean Consumption
joined_data <- mutate(joined_data, mean_consumption = rowMeans(meter_data[, c(2:337)]))

# Cumulated Consumption
joined_data <- mutate(joined_data, sum_consumption = rowSums(meter_data[, c(2:337)]))

# Night to noon ratio 23 - 0 vs 12 - 13
noon <- c()
for(i in c(0:1)) {
  data <- seq(from = 24 + i, to = 337, by = 48)
  noon <- sort(c(noon, data))
}
night <- c()
for(i in c(0:1)) {
  data <- seq(from = 46 + i, to = 337, by = 48)
  night <- sort(c(night, data))
}
joined_data <- mutate(joined_data, night_noon_consumption = rowMeans(meter_data[, night]) / rowMeans(meter_data[, noon]))

# Morning Consumption
morning <- c()
for(i in c(0:9)) {
  data <- seq(from = 14 + i, to = 337, by = 48)
  morning <- sort(c(morning, data))
}
joined_data <- mutate(joined_data, morning_consumption = rowMeans(meter_data[, morning]))

# Evening Consumption
evening <- c()
for(i in c(0:11)) {
  data <- seq(from = 36 + i, to = 337, by = 48)
  evening <- sort(c(evening, data))
}
joined_data <- mutate(joined_data, evening_consumption = rowMeans(meter_data[, evening]))

# Weekend Consumption

# Lunch(preparation)time Consumption (12:00 - 14:00)
lunchtime <- c()
for(i in c(0:3)) {
  data <- seq(from = 24 + i, to = 337, by = 48)
  lunchtime <- sort(c(lunchtime, data))
}

joined_data <- mutate(joined_data, lunchtime_consumption = rowMeans(meter_data[, lunchtime]))

# Dinner(preparation)time Consumption (18:00 - 20:00)
dinnertime <- c()
for(i in c(0:3)) {
  data <- seq(from = 36 + i, to = 337, by = 48)
  dinnertime <- sort(c(dinnertime, data))
}

joined_data <- mutate(joined_data, dinnerime_consumption = rowMeans(meter_data[, dinnertime]))

```

---
Exercise 2
---
```{r setup, include=FALSE}
# Split data set randomly into training set and test set
training_data_size <- floor(0.8 * nrow(joined_data))

set.seed(4815)

training_indices <- sample(seq_len(nrow(joined_data)), size = training_data_size)
training_data <- joined_data[training_indices,]
test_data <- joined_data[-training_indices,]

# Train the model
glm.fit <- glm(single ~ night_noon_consumption + highest_consumption + mean_consumption + dinnerime_consumption + lowest_consumption + lunchtime_consumption, family = binomial, data = training_data)

glm.probs <- predict(glm.fit, test_data, type = "response")

# splitting model into single and not-single houshold
splitted <- ifelse(glm.probs <= 0.5, "Not single","Single")
confusionmatrix <- table(splitted, test_data$single)
precious <- (sum(diag(confusionmatrix))/sum(as.vector(confusionmatrix))) #0.865

# five-fold cross validation
folding <- 5
joined_data$crossfold <- 1:folding
fold <- cut(seq(1, nrow(joined_data)), breaks=5, labels = FALSE)
listen <- list()


for(i in 1:folding) {
  testIndex <- which(joined_data$crossfold==i, arr.ind=TRUE)
  testData <- joined_data[testIndex, ]
  trainData <- joined_data[-testIndex, ]
  model <- glm(single ~ night_noon_consumption + highest_consumption + mean_consumption + dinnerime_consumption + lowest_consumption + lunchtime_consumption, family = binomial, data = training_data)
  
  listen[[i]]$model <- model
  prediction <- predict(model, testData, type ="response")
  prediction <- ifelse(prediction <= 0.5, "Not single","Single")
  listen[[i]]$confusionmatrix <- table(prediction, testData$single)
  
  listen[[i]]$accuracy <- (sum(diag(listen[[i]]$confusionmatrix))/sum(as.vector(listen[[i]]$confusionmatrix)))
}


# average of accuracy
vector <- c()
for(i in 1:folding) {
  vector <- c(vector,listen[[i]]$accuracy)
}
av_accuracy <- mean(vector)
standartdeviation <- sd(vector)

error <- qt(0.975, folding-1)*standartdeviation/sqrt(folding)

barplot <- ggplot(as.data.frame(av_accuracy), aes(x=1, y=av_accuracy)) + geom_bar(position = position_dodge(), stat = "identity") + geom_errorbar(aes(ymin = av_accuracy - error, ymax = av_accuracy + error), width = 0.5)



# guessing and biased guessing visualised by barplot
set.seed(8790)
random_counter <- 0
biased_counter <- 0

for(i in 1:nrow(joined_data)) {
  class <- joined_data[i, "single"]
  flips <- sample(c("Single", "Not single"), size = 1, replace = TRUE, prob = c(0.5, 0.5))
  if(class == flips) {
    random_counter <- random_counter + 1
  }
}

random_ac <- random_counter / nrow(joined_data)
single_counter <- nrow(joined_data %>% filter(single == "Single"))


for(i in 1:nrow(joined_data)) {
  class <- joined_data[i, "single"]
  flips <- sample(c("Single", "Not single"), size = 1, replace = TRUE, prob = c(1-single_counter/ nrow(joined_data), single_counter/ nrow(joined_data)))
  if(class == flips) {
    biased_counter <- biased_counter + 1
  }
}

biased_ac <- biased_counter / nrow(joined_data)

barplot <- ggplot(data.frame(accuracies = c("model accuracy", "random guess", "biased guess"), accuracies_value = c(av_accuracy, random_ac, biased_ac)), aes(x=accuracies, y=accuracies_value)) + geom_bar(stat="identity") + geom_bar(position = position_dodge(), stat = "identity") + geom_errorbar(aes(ymin = av_accuracy - error, ymax = av_accuracy + error), width = 0.5)



```
